# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish PNPM Package to NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.0.0
        name: Instal PNPM
        with:
          version: 9
          run_install: false

      - name: Install Node.JS
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish Package
        shell: bash
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{  secrets.NPM_TOKEN }}
